version: "3"
services: 
  node:
    image: "node"
    ports:
    - "2020:3000"
    working_dir: /home/node/
    volumes:
    - ./node:/home/node
    command: sh -c "npm install && npm run serve"