version: "3"
services: 
  node:
    image: "node"
    ports:
    - "2020:3000"
    working_dir: /home/node/
    volumes:
    - ./node:/home/node
    command: sh -c "npm install && npm run serve"
  java:
    image: "maven"
    ports: 
    - "2021:4000"
    working_dir: /usr/src/mymaven
    volumes:
    - ./java:/usr/src/mymaven
    command: mvn spring-boot:run
  mongo:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
